[tools]
bun = "latest"

[env]
_.file = ".env"
PROJECT_NAME = "{{ config_root | basename }}"

[vars]
PORT = "{{ env.PORT | default(value=3000) }}"

[tasks.dev]
alias = "d"
env = { NODE_ENV = "development" }
description = "Dev server for the frontend"
run = "vite dev --port {{vars.PORT}}"

[tasks.build]
alias = "b"
description = "Run a production build of the frontend"
env = { NODE_ENV = "production" }
run = "vite build"

[tasks.lint]
run = "bunx --bun biome check"
